Repository SrainApp/srain, pull requests merged in 2020-03, with the labels that each got.

#201 Add hackint irc network
  data/builtin.cfg
Labels: enhancement, mod-config

#202 Compare commands case-insensitively
  src/sirc/sirc_event_hdr.c
Labels: bug, mod-irc

#203 Replace Travis CI with Github actions.
  .github/workflows/build.yml
  .travis.yml
  .travis/build.sh
  .travis/dep.sh
  .travis/install.sh
  doc/install.rst
Labels: enhancement, mod-build

#204 Document configuration path for flatpak installs
  doc/config.rst
Labels: enhancement, mod-doc

#205 Use default button relief and use symbolic icons
  data/ui/window.glade
  src/sui/sui_side_bar.c
  src/sui/sui_window.c
Labels: enhancement, mod-ui

#214 Valid appdata file
  data/srain.appdata.xml
Labels: bug

#215 Added Dutch translation
  po/LANGS
  po/nl.po
Labels: mod-i18n

#216 Update dependency documentation
  doc/install.rst
Labels: mod-doc

#217 Update documentation about Debian installation
  README.rst
  doc/faq.rst
  doc/install.rst
  src/sui/sui_app.c
Labels: mod-doc, os-linux

#218 Move header bar buttons into button box
  data/themes/default-min.css
  data/ui/window.glade
  src/sui/sui_window.c
Labels: enhancement, mod-ui

#224 Script(update): allow setting CC variable via environment
  src/Makefile
Labels: enhancement, mod-build

#226 Add channel related errros to corresponding buffer
  src/core/app_irc_event.c
Labels: enhancement, mod-core

#229 Improve widget focus handling
  data/ui/window.glade
  src/sui/sui_connect_panel.c
  src/sui/sui_join_panel.c
  src/sui/sui_window.c
Labels: enhancement, mod-ui

#230 Fix wrong user statistic after reconnection
  src/sui/sui_user.c
  src/sui/sui_user_list.c
Labels: bug, mod-ui
