Repository SrainApp/srain, pull requests merged in 2020-04, with the labels that each got.

#232 Fix some lintian warning
  data/Makefile
  data/icons/128x128/srain-red.png
  data/icons/128x128/srain.png
  data/icons/scalable/srain-black.png
  data/icons/scalable/srain-red.png
  data/icons/scalable/srain.png
  data/srain.gresource.xml
  doc/Makefile
Labels: bug

#233 Improve error reporting
  po/nl.po
  po/ru.po
  po/srain.pot
  po/zh_CN.po
  src/core/app.c
  src/sui/sui_connect_panel.c
Labels: enhancement, mod-core, mod-ui

#228 Adding more pre-defined servers, as per file TODO
  data/builtin.cfg
Labels: enhancement, mod-config

#238 Add Github actions of the release event.
  .github/workflows/release-assets-upload.py
  .github/workflows/release-debian-package.sh
  .github/workflows/release.yml
Labels: mod-build
